credentials_file = "./resources/credentials.json"
default_region   = "us-west1"
default_zone     = "us-west1-b"
function_region  = "us-central1"
app_region       = "us-west2"
initial_image    = "ubuntu-1804-bionic-v20200317"
gpu_type         = "nvidia-tesla-p100"
instance_prefix  = "folding"
gpu_count        = 1 # GPUs per instance
machine_type     = "n1-highcpu-2"
machine_count    = 1 # Number of instances